### ISSUE TITLE
How to pass variable to filter?

### ISSUE THREAD

**Issue by acelot** [phug-php/phug#33]
Hello,

I encountered an issue with the following code:
```pug
span
  :format-date('DD-MM-YYY')
    $article['publication_date']
```

`$article['publication_date']` is a DateTime.

I expected to get:
```html
<span>30-03-2018</span>
```

But I actually get:
```
[TypeError] Argument 1 passed to {closure}() must be an instance of DateTime, string given
```

My Renderer instance:
```php
$renderer = new \Phug\Renderer([
    'filters' => [
        'format-date' => function (\DateTime $date, $args = []) {
            return $date->format($args[0]);
        }
    ]
]);
```

**Comment by kylekatarnls** [comment]
Filters have options (attributes), no arguments:
```pug
span
  :format-date(format='DD-MM-YYY')
    $article['publication_date']
```
```php
$renderer = new \Phug\Renderer([
    'filters' => [
        'format-date' => function (\DateTime $date, $options) {
            return $date->format($options['format']);
        },
    ],
]);
```

Please tell me if you get trouble, I will re-open this issue.

**Comment by acelot** [comment]
@kylekatarnls the problem is not about getting an options in filter. Problem is to pass value (variable) into filter. Is it correct to pass a **variable** to filter as in a template? Because I'm getting `[string] "$article['publication_date']"` instead of `\DateTime` instance in `$date` argument.

**Comment by TorbenKoehn** [comment]
Hello,

the content of a filter is usually given in plain-text, since it can be anything (e.g. JavaScript, CSS or something completely different like Markdown or even pure PHP)
The filter is responsible for parsing the text content.

A better way to format dates within Pug is by using normal PHP functions

```pug
span= $article['publication_date']->format('d-m-Y')
```

It's also more pure and looks better, PHP-wise :)

-----

Edit:
If you really want to pass it as an option, you could probably use something like this:

```pug
span
    :format-date(format='DD-MM-YYYY', value=$article['publication_date'])
```

and then

```php
$renderer = new \Phug\Renderer([
    'filters' => [
        'format-date' => function ($content, $options) {
            return $options['value']->format($options['format']);
        },
    ],
]);
```

but as you can see, it's rather redundant
