### ISSUE TITLE
Parsing error using JsPhpizePhug

### ISSUE THREAD

**Issue by BananaAcid** [phug-php/phug#59]
Hello,

Since I am not sure, where this goes, I cross-posted it here: https://github.com/pug-php/js-phpize/issues/31

Working on pugjs, I get with Phug

![image](https://user-images.githubusercontent.com/1894723/77824204-3c5f3580-7101-11ea-911a-ccbf8e95414b.png)

and

![image](https://user-images.githubusercontent.com/1894723/77824374-8c8ac780-7102-11ea-8961-055ce2dbaf07.png)

`[].concat`, `Object.keys()` does not seem to work ...

Thanks!

**Comment by kylekatarnls** [comment]
Indeed, we don't have `Object.*` polyfill at all. But you can rely on PHP functions:

```pug
- tags = array_merge(tags, array_keys(attributes))
```

I know this make the mixin not compatible in JS env, but I would argue you should avoid having multiple ways of doing the same thing and attributes are not supposed to be used this way.

**Comment by BananaAcid** [comment]
Doing the php line you mentioned, I would need to change everything to PHP? It won't cross compile anymore, I believe.

**Comment by kylekatarnls** [comment]
It's still PHP behind to make you benefit of direct access to objects and functions of your application. We won't rewrite the whole node.js engine in PHP to make every possible JS code compatible inside pug templates. That's not the purpose. We provide basic polyfills to make simple expressions in JS syntax.

That should be enough because templates are meant to be just display and formatting, algorithm and more complex logic should be handled behind in your controllers and services. In your case you could have a function "merge_attributes_keys" doing this and implement the same function in JS to use concat. And so the template would compile in both JS and PHP env.

**Comment by BananaAcid** [comment]
> polyfills to make simple expressions in JS syntax

I undersand, ES5/ES6 would be out of scrope.

> "merge_attributes_keys" doing this and implement the same function in JS to use concat. And so the template would compile in both JS and PHP env."

Ok, this would be the solution, since "JS Style vaiables and function calls" are handled

Thank you!!
