### ISSUE TITLE
PHP 8.2 deprecations

### ISSUE THREAD

**Issue by alessandro-fazzi** [phug-php/phug#94]
Hello,

sorry for not using the issue template, but I'm just willing to report some deprecations encountered using PHP 8.2

- `Deprecated: mb_strlen(): Passing null to parameter #1 ($string) of type string is deprecated in vendor/phug/phug/src/Phug/Lexer/Lexer/Scanner/IndentationScanner.php on line 101`
- `Deprecated: str_repeat(): Passing null to parameter #1 ($string) of type string is deprecated in vendor/phug/phug/src/Phug/Lexer/Lexer/State.php on line 332`
- `Deprecated: str_repeat(): Passing null to parameter #2 ($times) of type int is deprecated in vendor/phug/phug/src/Phug/Lexer/Lexer/State.php on line 332`

IDK if it's useful, if not or if 1 issue per deprecation would have been better.

**Comment by kylekatarnls** [comment]
In the last version the `#[\ReturnTypeWillChange]` are already there:

For instance Phug\Ast\Node: https://github.com/phug-php/phug/blob/master/src/Phug/Ast/Ast/Node.php#L422

It has been fixed in https://github.com/phug-php/phug/commit/9dcb857bef090f3bc4d60e9fb64dba4b4461cbb2 (released in 2021: https://github.com/phug-php/phug/releases/tag/1.9.0)

Can you check which version you use please?

**Comment by alessandro-fazzi** [comment]
I'm on `pug-php/pug` 3.5 as the only explicit requirement.
Looking into the .lock I notice that it requires phug ^1.6, but I've got locked the 1.8.1, not the latest. Evidently this is just a project-related human big fail in the upgrade process.

Thanks for pointing that out.

Going to clean up the issue description removing the non relevant deprecations
